"""One way to read a source's catalogue, whatever format it speaks.

An Xtream subscription and an M3U playlist differ in exactly one thing: how the
catalogue is obtained. Xtream answers a typed API — categories have ids, streams
arrive classified, a series hands over its seasons on request, and a stream URL
is rebuilt from the credentials. An M3U is one flat text file: no categories but
``group-title`` strings, no types but what the URL and the title betray, and the
URL given verbatim.

So the adapters below expose the *same* surface — deliberately the one
``XtreamClient`` already had, because that is the shape the sync, the downloads,
the live resolution and the organiser were all written against. Nothing else in
the application needs to know which kind of source it is holding.

The Xtream adapter is ``XtreamClient`` itself. The M3U adapter parses the
playlist into ``source_entries`` once, then answers from those rows.
"""

from __future__ import annotations

import hashlib
import logging
import os
import re
import time
from datetime import datetime, timedelta
from typing import Dict, List, Optional
from urllib.parse import urlparse

from sqlalchemy.orm import Session

from app.core.redis import redis_conn
from app.models.source_entry import EntryType, SourceEntry
from app.models.subscription import M3USourceType, SourceKind, Subscription
from app.services.m3u_parser import parse_m3u_file, parse_m3u_url
from app.services.xtream import XtreamClient

logger = logging.getLogger(__name__)

# How long a playlist may go without being read again. A full M3U is a single
# large download, and both the movie and the series sync ask for it.
_REPARSE_AFTER = timedelta(hours=1)

# Extensions that mean "a file", i.e. video on demand. A live stream ends in
# .ts, .m3u8 or nothing at all.
_VOD_EXTENSIONS = {"mp4", "mkv", "avi", "mov", "m4v", "flv", "wmv", "mpg", "mpeg"}

# "S01 E02", "S01E02", "s1.e2" — and the "1x02" form some playlists use.
_SXXEXX = re.compile(r"(?i)\bS\s*(?P<season>\d{1,3})\s*[\s._x-]*\s*E\s*(?P<episode>\d{1,4})\b")
_NXNN = re.compile(r"(?i)(?<![\d.])(?P<season>\d{1,2})\s*x\s*(?P<episode>\d{1,3})(?![\d])")


def _extension_of(url: str) -> str:
    """The extension the URL ends with, lowercased and without the dot."""
    path = urlparse(url or "").path
    _, _, ext = path.rpartition(".")
    ext = ext.lower()
    # A path segment with no dot leaves the whole path in `ext`.
    return ext if ext and "/" not in ext and len(ext) <= 5 else ""


def _split_episode(title: str):
    """(series name, season, episode) if the title names one, else None."""
    for pattern in (_SXXEXX, _NXNN):
        found = pattern.search(title or "")
        if not found:
            continue
        name = (title[:found.start()] or "").strip(" -–—_.|[]()")
        if not name:
            # "S01E02 - Pilot" with nothing before it: the show has no name to
            # take from the title, so the group will have to serve as one.
            name = ""
        return name, int(found.group("season")), int(found.group("episode"))
    return None


def classify(entry: dict) -> dict:
    """Decide what one parsed playlist line actually is.

    The URL is authoritative when it says so — a playlist generated by an Xtream
    panel puts /series/ and /movie/ in the path — and the title is the fallback
    for the hand-written playlists that have neither.
    """
    url = entry.get("url") or ""
    title = entry.get("title") or ""
    ext = _extension_of(url)

    parsed_episode = _split_episode(title)

    if "/series/" in url:
        kind = EntryType.SERIES
    elif "/movie/" in url:
        kind = EntryType.MOVIE
    elif parsed_episode:
        kind = EntryType.SERIES
    elif ext in _VOD_EXTENSIONS:
        kind = EntryType.MOVIE
    else:
        kind = EntryType.LIVE

    result = {
        "entry_type": kind,
        "container": ext or ("ts" if kind == EntryType.LIVE else "mp4"),
        "series_key": None,
        "season": None,
        "episode": None,
    }

    if kind == EntryType.SERIES:
        if parsed_episode:
            name, season, episode = parsed_episode
            result["series_key"] = name or (entry.get("group_title") or title)
            result["season"] = season
            result["episode"] = episode
        else:
            # An Xtream /series/ URL whose title says nothing about numbering:
            # the title is the show, and it gets a single S01E01.
            result["series_key"] = title
            result["season"] = 1
            result["episode"] = 1

    return result


def _stable_id(*parts) -> int:
    """A deterministic 60-bit id for something the playlist does not number.

    A series has no id in an M3U, but the cache, the selection and the library
    layout all key on one, and it must not move between two syncs or every show
    would be rewritten. Derived from the source and the show name, so it is the
    same on every run and different for every show.
    """
    digest = hashlib.sha1("|".join(str(p) for p in parts).encode("utf-8")).hexdigest()
    return int(digest[:15], 16)


class M3UCatalog:
    """The catalogue of an M3U source, in the shape ``XtreamClient`` returns.

    The playlist is parsed into ``source_entries`` on first use and re-read when
    it goes stale. Every accessor below answers from those rows.
    """

    def __init__(self, db: Session, subscription: Subscription, force_reparse: bool = False):
        self.db = db
        self.subscription = subscription
        self.subscription_id = subscription.id
        self._force = force_reparse
        self._loaded = False
        self._entries: List[SourceEntry] = []
        self._url_by_id: Dict[int, str] = {}

    # -- parsing ---------------------------------------------------------

    def _is_stale(self) -> bool:
        last = self.subscription.last_sync
        if not last:
            return True
        return (datetime.utcnow() - last) >= _REPARSE_AFTER

    def _read_playlist(self) -> List[dict]:
        if self.subscription.source_type == M3USourceType.FILE.value:
            if not self.subscription.file_path or not os.path.exists(self.subscription.file_path):
                raise FileNotFoundError(
                    f"The playlist file for {self.subscription.name} is missing: "
                    f"{self.subscription.file_path}"
                )
            return parse_m3u_file(self.subscription.file_path)
        if not self.subscription.url:
            raise ValueError(f"Source {self.subscription.name} has no playlist URL")
        return parse_m3u_url(self.subscription.url)

    @property
    def _lock_key(self) -> str:
        return f"m3u:parse:{self.subscription_id}"

    def _acquire_parse_lock(self) -> bool:
        """True if this process may parse. Never blocks the parse on Redis
        being unavailable — a missing lock is a race, a hard failure here would
        be an outage."""
        try:
            return bool(redis_conn.set(self._lock_key, "1", nx=True, ex=900))
        except Exception as e:
            logger.warning("Parse lock unavailable for %s (%s); parsing anyway.",
                           self.subscription.name, e)
            return True

    def _release_parse_lock(self) -> None:
        try:
            redis_conn.delete(self._lock_key)
        except Exception:
            pass

    def _await_parse(self, timeout: int = 300) -> None:
        """Wait for whoever holds the lock to finish writing the rows."""
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            try:
                if not redis_conn.exists(self._lock_key):
                    return
            except Exception:
                return
            time.sleep(1)
        logger.warning("Timed out waiting for the parse of %s; reading what is "
                       "already there.", self.subscription.name)

    def ensure_parsed(self, force: bool = False) -> int:
        """Read the playlist into ``source_entries`` if needed. Returns the count.

        The rows are only replaced once the new playlist has been read: a source
        that fails to download must leave the previous catalogue in place, or a
        transient error would present itself downstream as "the provider has
        nothing", which is what empties a library.
        """
        if self._loaded and not force:
            return len(self._entries)

        existing = self.db.query(SourceEntry).filter(
            SourceEntry.subscription_id == self.subscription_id
        ).count()

        if not (force or self._force or existing == 0 or self._is_stale()):
            self._load_rows()
            return len(self._entries)

        # The movie sync and the series sync of one source run as two Celery
        # tasks with two sessions. Both would parse, and their delete-then-
        # insert passes interleave into a doubled or truncated catalogue. The
        # first one through does the work; the second waits and reads the rows.
        if not self._acquire_parse_lock():
            self._await_parse()
            self._load_rows()
            return len(self._entries)

        try:
            return self._parse_into_rows(existing)
        finally:
            self._release_parse_lock()

    def _parse_into_rows(self, existing: int) -> int:
        raw_entries = self._read_playlist()
        logger.info("Parsed %s entries from playlist %s", len(raw_entries),
                    self.subscription.name)

        if not raw_entries and existing:
            # An empty parse of a playlist we already know is not news, it is a
            # failure. Keep what we have and let the caller's own guard speak.
            logger.warning("Playlist %s parsed empty while %s entries are known — "
                           "keeping the previous catalogue.",
                           self.subscription.name, existing)
            self._load_rows()
            return len(self._entries)

        self.db.query(SourceEntry).filter(
            SourceEntry.subscription_id == self.subscription_id
        ).delete()

        for raw in raw_entries:
            if not raw.get("url"):
                continue
            facts = classify(raw)
            self.db.add(SourceEntry(
                subscription_id=self.subscription_id,
                title=raw.get("title") or "Unknown",
                url=raw["url"],
                group_title=raw.get("group_title"),
                logo=raw.get("logo"),
                tvg_id=raw.get("tvg_id"),
                tvg_name=raw.get("tvg_name"),
                entry_type=facts["entry_type"],
                series_key=facts["series_key"],
                season=facts["season"],
                episode=facts["episode"],
                container=facts["container"],
                catchup=raw.get("catchup"),
                catchup_days=raw.get("catchup_days"),
                catchup_source=raw.get("catchup_source"),
            ))

        self.db.commit()
        self._load_rows()
        return len(self._entries)

    def _load_rows(self) -> None:
        self._entries = self.db.query(SourceEntry).filter(
            SourceEntry.subscription_id == self.subscription_id
        ).all()
        self._url_by_id = {e.id: e.url for e in self._entries}
        self._loaded = True

    def _of_type(self, entry_type: str) -> List[SourceEntry]:
        self.ensure_parsed()
        return [e for e in self._entries if e.entry_type == entry_type]

    # -- categories ------------------------------------------------------
    # A group title is its own id. `selected_categories.category_id` is text on
    # both sides, so nothing had to change for this to be selectable.

    def _categories(self, entry_type: str) -> List[Dict]:
        groups = []
        seen = set()
        for entry in self._of_type(entry_type):
            group = entry.group_title or "Uncategorized"
            if group in seen:
                continue
            seen.add(group)
            groups.append({"category_id": group, "category_name": group})
        return sorted(groups, key=lambda c: c["category_name"].lower())

    async def get_vod_categories(self) -> List[Dict]:
        return self._categories(EntryType.MOVIE)

    def get_vod_categories_sync(self) -> List[Dict]:
        return self._categories(EntryType.MOVIE)

    async def get_series_categories(self) -> List[Dict]:
        return self._categories(EntryType.SERIES)

    def get_series_categories_sync(self) -> List[Dict]:
        return self._categories(EntryType.SERIES)

    async def get_live_categories(self) -> List[Dict]:
        return self._categories(EntryType.LIVE)

    def get_live_categories_sync(self) -> List[Dict]:
        return self._categories(EntryType.LIVE)

    # -- movies ----------------------------------------------------------

    def _vod_streams(self, category_id: Optional[str] = None) -> List[Dict]:
        out = []
        for entry in self._of_type(EntryType.MOVIE):
            group = entry.group_title or "Uncategorized"
            if category_id and group != category_id:
                continue
            out.append({
                "stream_id": entry.id,
                "name": entry.title,
                "category_id": group,
                "container_extension": entry.container or "mp4",
                "stream_icon": entry.logo or "",
                "tmdb": None,
            })
        return out

    async def get_vod_streams(self, category_id: Optional[str] = None) -> List[Dict]:
        return self._vod_streams(category_id)

    def get_vod_streams_sync(self, category_id: Optional[str] = None) -> List[Dict]:
        return self._vod_streams(category_id)

    async def get_vod_info(self, vod_id: str) -> Dict:
        # A playlist carries no metadata beyond the line itself.
        return {}

    def get_vod_info_sync(self, vod_id: str) -> Dict:
        return {}

    # -- series ----------------------------------------------------------

    def _series_rows(self) -> Dict[int, Dict]:
        """Group the episode lines into shows, keyed by their stable id."""
        shows: Dict[int, Dict] = {}
        for entry in self._of_type(EntryType.SERIES):
            group = entry.group_title or "Uncategorized"
            name = entry.series_key or entry.title
            series_id = _stable_id(self.subscription_id, group, name)
            show = shows.setdefault(series_id, {
                "series_id": series_id,
                "name": name,
                "category_id": group,
                "cover": entry.logo or "",
                "tmdb": None,
                "_episodes": [],
            })
            show["_episodes"].append(entry)
        return shows

    def _series(self, category_id: Optional[str] = None) -> List[Dict]:
        out = []
        for show in self._series_rows().values():
            if category_id and show["category_id"] != category_id:
                continue
            episodes = show["_episodes"]
            listing = {k: v for k, v in show.items() if k != "_episodes"}
            # Stands in for the provider's `last_modified`: it moves as soon as
            # the show gains, loses or renumbers an episode, which is exactly
            # when the sync must rewrite the folder.
            listing["last_modified"] = _stable_id(
                len(episodes), *sorted(e.id for e in episodes)
            )
            out.append(listing)
        return out

    async def get_series(self, category_id: Optional[str] = None) -> List[Dict]:
        return self._series(category_id)

    def get_series_sync(self, category_id: Optional[str] = None) -> List[Dict]:
        return self._series(category_id)

    def _series_info(self, series_id: str) -> Dict:
        show = self._series_rows().get(int(series_id))
        if not show:
            return {"info": {}, "episodes": {}}

        seasons: Dict[str, List[Dict]] = {}
        for entry in show["_episodes"]:
            season = entry.season or 1
            seasons.setdefault(str(season), []).append({
                "id": entry.id,
                "episode_num": entry.episode or 1,
                "container_extension": entry.container or "mp4",
                "title": entry.title,
            })
        for episodes in seasons.values():
            episodes.sort(key=lambda e: e["episode_num"])

        return {
            "info": {"name": show["name"], "cover": show["cover"]},
            "episodes": seasons,
        }

    async def get_series_info(self, series_id: str) -> Dict:
        return self._series_info(series_id)

    def get_series_info_sync(self, series_id: str) -> Dict:
        return self._series_info(series_id)

    # -- live ------------------------------------------------------------

    def _live_streams(self, category_id: Optional[str] = None) -> List[Dict]:
        out = []
        for entry in self._of_type(EntryType.LIVE):
            group = entry.group_title or "Uncategorized"
            if category_id and group != category_id:
                continue
            out.append({
                "stream_id": entry.id,
                "name": entry.title,
                "category_id": group,
                "epg_channel_id": entry.tvg_id or "",
                "stream_icon": entry.logo or "",
                # Replay, in the shape the Xtream listing uses, plus the two
                # M3U-only fields. This used to be a hardcoded `tv_archive: 0`,
                # which threw away the only thing the playlist knew about
                # catch-up and left the channel without a replay button.
                "tv_archive": 1 if (entry.catchup or entry.catchup_days) else 0,
                "tv_archive_duration": entry.catchup_days or 0,
                "catchup": entry.catchup or "",
                "catchup_source": entry.catchup_source or "",
                "direct_source": entry.url,
            })
        return out

    async def get_live_streams(self, category_id: Optional[str] = None) -> List[Dict]:
        return self._live_streams(category_id)

    def get_live_streams_sync(self, category_id: Optional[str] = None) -> List[Dict]:
        return self._live_streams(category_id)

    # -- resolution ------------------------------------------------------

    def get_stream_url(self, stream_type: str, stream_id: str, extension: str = "") -> str:
        """The URL the playlist gave for this entry, verbatim.

        There is nothing to rebuild: an M3U line *is* its URL. The signature
        matches the Xtream client's so that the callers do not branch.
        """
        try:
            entry_id = int(stream_id)
        except (TypeError, ValueError):
            return ""
        if entry_id in self._url_by_id:
            return self._url_by_id[entry_id]

        entry = self.db.query(SourceEntry).filter(
            SourceEntry.id == entry_id,
            SourceEntry.subscription_id == self.subscription_id,
        ).first()
        return entry.url if entry else ""


def get_catalog(db: Session, subscription: Subscription, force_reparse: bool = False):
    """The adapter that reads this source's catalogue.

    Callers hold the result and never ask what kind of source it came from.
    """
    if subscription.kind == SourceKind.M3U.value:
        return M3UCatalog(db, subscription, force_reparse=force_reparse)
    return XtreamClient(subscription.xtream_url, subscription.username,
                        subscription.password)
